# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source $(brew --prefix)/share/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load bundles from oh-my-zsh repo
antigen bundles <<EOBUNDLES
    git
    autojump
EOBUNDLES

# Load bundles from external repos
antigen bundles <<EOBUNDLES
    Aloxaf/fzf-tab
EOBUNDLES

# Load bundles from zsh-users repos
antigen bundles <<EOBUNDLES
    zsh-users/zsh-autosuggestions
    zsh-users/zsh-completions
    zsh-users/zsh-syntax-highlighting
EOBUNDLES

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

antigen theme romkatv/powerlevel10k

# 1Passwort SSH-Agent integration
# https://developer.1password.com/docs/ssh/get-started#step-4-configure-your-ssh-or-git-client
export SSH_AUTH_SOCK=~/.1password/agent.sock

# SDKMAN-CLI integration
# https://github.com/sdkman/homebrew-tap
export SDKMAN_DIR=$(brew --prefix sdkman-cli)/libexec
[[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"

# fzf git integration
# https://github.com/junegunn/fzf-git.sh
[[ ! -f ~/.fzf-git.sh ]] || source ~/.fzf-git.sh

# 3. Commit Antigen Configuration
antigen apply
